version: '3.5'
services:
  api:
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
      target: build
    container_name: l-semi-chat-api
    environment:
      MYSQL_USER: worker
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ls_chat
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FILE_PATH: /images
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    restart: always
    command: realize start

  db:
    image: mysql:5.7
    container_name: l-semi-chat-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ls_chat
      MYSQL_USER: worker
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # この辺は必要なら適宜
      - ./db/mysql/init.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    restart: always

  redis:
    image: redis:6.2.4
    container_name: l-semi-token-db
    command: redis-server --bind 0.0.0.0 --port 6379
    environment: 
      REDIS_PASSWORD: password
    ports:
      - "6379:6379"
    restart: always
